In [70]:
import pandas as pd
from dataprep.datasets import load_dataset
from dataprep.eda import create_report
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from matplotlib import pyplot as plt 
import seaborn as sns
from sklearn import svm
import pickle

In [127]:
df = pd.read_csv("F:/spaceship-titanic/train.csv")
#df = df.drop(["Transported"],axis=1)
#Y = df["Transported"]

In [128]:
X = df.drop(["Transported"],axis=1)
Y = df["Transported"]

In [129]:
df1 = pd.read_csv("F:/spaceship-titanic/test.csv")

frames = [X, df1]
df_total = pd.concat(frames)

In [130]:
df_total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12970 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   12970 non-null  object 
 1   HomePlanet    12682 non-null  object 
 2   CryoSleep     12660 non-null  object 
 3   Cabin         12671 non-null  object 
 4   Destination   12696 non-null  object 
 5   Age           12700 non-null  float64
 6   VIP           12674 non-null  object 
 7   RoomService   12707 non-null  float64
 8   FoodCourt     12681 non-null  float64
 9   ShoppingMall  12664 non-null  float64
 10  Spa           12686 non-null  float64
 11  VRDeck        12702 non-null  float64
 12  Name          12676 non-null  object 
dtypes: float64(6), object(7)
memory usage: 1.4+ MB


In [131]:
df_total['CryoSleep'].unique()

array([False, True, nan], dtype=object)

In [132]:
df_total.shape

(12970, 13)

In [147]:
df_total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12970 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   PassengerId   12970 non-null  object 
 1   HomePlanet    12682 non-null  object 
 2   CryoSleep     12660 non-null  object 
 3   Cabin         12671 non-null  object 
 4   Destination   12696 non-null  object 
 5   Age           12700 non-null  float64
 6   VIP           12674 non-null  object 
 7   RoomService   12707 non-null  float64
 8   FoodCourt     12681 non-null  float64
 9   ShoppingMall  12664 non-null  float64
 10  Spa           12686 non-null  float64
 11  VRDeck        12702 non-null  float64
 12  Name          12676 non-null  object 
dtypes: float64(6), object(7)
memory usage: 1.4+ MB


In [148]:
df_total.columns


Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name'],
      dtype='object')

In [149]:
df_new = df_total.drop(["PassengerId"],axis=1)

df_new.columns

Index(['HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age', 'VIP',
       'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Name'],
      dtype='object')

In [150]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12970 entries, 0 to 4276
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   HomePlanet    12682 non-null  object 
 1   CryoSleep     12660 non-null  object 
 2   Cabin         12671 non-null  object 
 3   Destination   12696 non-null  object 
 4   Age           12700 non-null  float64
 5   VIP           12674 non-null  object 
 6   RoomService   12707 non-null  float64
 7   FoodCourt     12681 non-null  float64
 8   ShoppingMall  12664 non-null  float64
 9   Spa           12686 non-null  float64
 10  VRDeck        12702 non-null  float64
 11  Name          12676 non-null  object 
dtypes: float64(6), object(6)
memory usage: 1.3+ MB


In [151]:
df_new.isnull().sum()

HomePlanet      288
CryoSleep       310
Cabin           299
Destination     274
Age             270
VIP             296
RoomService     263
FoodCourt       289
ShoppingMall    306
Spa             284
VRDeck          268
Name            294
dtype: int64

In [152]:
df_new['VIP'].unique()

array([False, True, nan], dtype=object)

In [153]:
df_new['Deck'] = df_new['Cabin'].str.split('/',expand=True)[0]
df_new['side'] = df_new['Cabin'].str.split('/',expand=True)[2]

In [154]:
df_new['Deck'].unique(),df_new['side'].unique()

(array(['B', 'F', 'A', 'G', nan, 'E', 'D', 'C', 'T'], dtype=object),
 array(['P', 'S', nan], dtype=object))

In [155]:
df_new1= df_new.drop(['Cabin'],axis=1)

In [156]:
df_new1

HomePlanet CryoSleep    Destination   Age    VIP  RoomService  FoodCourt  \
0        Europa     False    TRAPPIST-1e  39.0  False          0.0        0.0   
1         Earth     False    TRAPPIST-1e  24.0  False        109.0        9.0   
2        Europa     False    TRAPPIST-1e  58.0   True         43.0     3576.0   
3        Europa     False    TRAPPIST-1e  33.0  False          0.0     1283.0   
4         Earth     False    TRAPPIST-1e  16.0  False        303.0       70.0   
...         ...       ...            ...   ...    ...          ...        ...   
4272      Earth      True    TRAPPIST-1e  34.0  False          0.0        0.0   
4273      Earth     False    TRAPPIST-1e  42.0  False          0.0      847.0   
4274       Mars      True    55 Cancri e   NaN  False          0.0        0.0   
4275     Europa     False            NaN   NaN  False          0.0     2680.0   
4276      Earth      True  PSO J318.5-22  43.0  False          0.0        0.0   

      ShoppingMall     Spa  VRDeck               Name Deck side  
0              0.0     0.0     0.0    Maham Ofracculy    B    P  
1             25.0   549.0    44.0       Juanna Vines    F    S  
2              0.0  6715.0    49.0      Altark Susent    A    S  
3            371.0  3329.0   193.0       Solam Susent    A    S  
4            151.0   565.0     2.0  Willy Santantines    F    S  
...            ...     ...     ...                ...  ...  ...  
4272           0.0     0.0     0.0        Jeron Peter    G    S  
4273          17.0    10.0   144.0      Matty Scheron  NaN  NaN  
4274           0.0     0.0     0.0        Jayrin Pore    D    P  
4275           0.0     0.0   523.0     Kitakan Conale    D    P  
4276           0.0     0.0     0.0   Lilace Leonzaley    G    S  

[12970 rows x 13 columns]

In [157]:
df_new1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12970 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   HomePlanet    12682 non-null  object 
 1   CryoSleep     12660 non-null  object 
 2   Destination   12696 non-null  object 
 3   Age           12700 non-null  float64
 4   VIP           12674 non-null  object 
 5   RoomService   12707 non-null  float64
 6   FoodCourt     12681 non-null  float64
 7   ShoppingMall  12664 non-null  float64
 8   Spa           12686 non-null  float64
 9   VRDeck        12702 non-null  float64
 10  Name          12676 non-null  object 
 11  Deck          12671 non-null  object 
 12  side          12671 non-null  object 
dtypes: float64(6), object(7)
memory usage: 1.4+ MB


In [158]:
df_new1.shape

(12970, 13)

In [326]:
rs = np.random.RandomState(0)
df = pd.DataFrame(rs.rand(10, 10))
corr = df_new1.corr()
corr.style.background_gradient(cmap='coolwarm')
# 'RdBu_r', 'BrBG_r', & PuOr_r are other good diverging colormaps

In [159]:
df_new1['VIP'].unique(),df_new1['CryoSleep'].unique()

(array([False, True, nan], dtype=object),
 array([False, True, nan], dtype=object))

In [160]:
# From the above pre-processing we can see
# Colums like " Destination" ,"VIP ""cryosleep" are kind of inbalanced data set
# Luxury terms are mostly skewed towards zero
# Lets pre-process the whole data set

from sklearn.base import TransformerMixin
import pandas as pd
import numpy as np

class DataFrameImputer(TransformerMixin):

    def __init__(self):
        """Impute missing values.

        Columns of dtype object are imputed with the most frequent value 
        in column.

        Columns of other types are imputed with mean of column.

        """
    def fit(self, X, y=None):

        self.fill = pd.Series([X[c].value_counts().index[0]
            if X[c].dtype == np.dtype('O') else X[c].median() for c in X],
            index=X.columns)

        return self

    def transform(self, X, y=None):
      
        return X.fillna(self.fill)

In [161]:
df_tr = pd.DataFrame(df_new1)
df_final = DataFrameImputer().fit_transform(df_tr)

In [162]:
df_final.isnull().sum()

HomePlanet      0
CryoSleep       0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Deck            0
side            0
dtype: int64

In [163]:
df_final['VIP'].unique()

array([False,  True])

In [164]:
df_final['HomePlanet'].unique()

array(['Europa', 'Earth', 'Mars'], dtype=object)

In [165]:
df_final['CryoSleep'].unique()

array([False,  True])

In [166]:
df_final.shape

(12970, 13)

In [167]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12970 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   HomePlanet    12970 non-null  object 
 1   CryoSleep     12970 non-null  bool   
 2   Destination   12970 non-null  object 
 3   Age           12970 non-null  float64
 4   VIP           12970 non-null  bool   
 5   RoomService   12970 non-null  float64
 6   FoodCourt     12970 non-null  float64
 7   ShoppingMall  12970 non-null  float64
 8   Spa           12970 non-null  float64
 9   VRDeck        12970 non-null  float64
 10  Name          12970 non-null  object 
 11  Deck          12970 non-null  object 
 12  side          12970 non-null  object 
dtypes: bool(2), float64(6), object(5)
memory usage: 1.2+ MB


In [168]:
df_final.isna().sum()

HomePlanet      0
CryoSleep       0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Deck            0
side            0
dtype: int64

In [169]:
Y.info(),df_final.info()

<class 'pandas.core.series.Series'>
RangeIndex: 8693 entries, 0 to 8692
Series name: Transported
Non-Null Count  Dtype
--------------  -----
8693 non-null   bool 
dtypes: bool(1)
memory usage: 8.6 KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 12970 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   HomePlanet    12970 non-null  object 
 1   CryoSleep     12970 non-null  bool   
 2   Destination   12970 non-null  object 
 3   Age           12970 non-null  float64
 4   VIP           12970 non-null  bool   
 5   RoomService   12970 non-null  float64
 6   FoodCourt     12970 non-null  float64
 7   ShoppingMall  12970 non-null  float64
 8   Spa           12970 non-null  float64
 9   VRDeck        12970 non-null  float64
 10  Name          12970 non-null  object 
 11  Deck          12970 non-null  object 
 12  side          12970 non-null  object 
dtypes: bool(2), float64(6), object(5)
memory u

(None, None)

In [170]:
df_final.shape

(12970, 13)

In [171]:
df_final['CryoSleep'].unique()

array([False,  True])

In [330]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12970 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   HomePlanet    12970 non-null  object 
 1   CryoSleep     12970 non-null  bool   
 2   Destination   12970 non-null  object 
 3   Age           12970 non-null  float64
 4   VIP           12970 non-null  bool   
 5   RoomService   12970 non-null  float64
 6   FoodCourt     12970 non-null  float64
 7   ShoppingMall  12970 non-null  float64
 8   Spa           12970 non-null  float64
 9   VRDeck        12970 non-null  float64
 10  Name          12970 non-null  object 
 11  Deck          12970 non-null  object 
 12  side          12970 non-null  object 
dtypes: bool(2), float64(6), object(5)
memory usage: 1.7+ MB


In [386]:
df_final['HomePlanet'].unique()

array(['Europa', 'Earth', 'Mars'], dtype=object)

In [332]:

import seaborn as sns
rs = np.random.RandomState(0)
df = pd.DataFrame(rs.rand(10, 10))
corr = df_final.corr()
corr.style.background_gradient(cmap='coolwarm')
# 'RdBu_r', 'BrBG_r', & PuOr_r are other good diverging colormaps

In [387]:
df_final1 = df_final.drop(["Name"],axis=1)

In [388]:
df_final1.columns

Index(['HomePlanet', 'CryoSleep', 'Destination', 'Age', 'VIP', 'RoomService',
       'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Deck', 'side'],
      dtype='object')

In [389]:
df_final2 = pd.get_dummies(df_final1)

In [390]:
df_final2

CryoSleep   Age    VIP  RoomService  FoodCourt  ShoppingMall     Spa  \
0         False  39.0  False          0.0        0.0           0.0     0.0   
1         False  24.0  False        109.0        9.0          25.0   549.0   
2         False  58.0   True         43.0     3576.0           0.0  6715.0   
3         False  33.0  False          0.0     1283.0         371.0  3329.0   
4         False  16.0  False        303.0       70.0         151.0   565.0   
...         ...   ...    ...          ...        ...           ...     ...   
4272       True  34.0  False          0.0        0.0           0.0     0.0   
4273      False  42.0  False          0.0      847.0          17.0    10.0   
4274       True  27.0  False          0.0        0.0           0.0     0.0   
4275      False  27.0  False          0.0     2680.0           0.0     0.0   
4276       True  43.0  False          0.0        0.0           0.0     0.0   

      VRDeck  HomePlanet_Earth  HomePlanet_Europa  ...  Deck_A  Deck_B  \
0        0.0                 0                  1  ...       0       1   
1       44.0                 1                  0  ...       0       0   
2       49.0                 0                  1  ...       1       0   
3      193.0                 0                  1  ...       1       0   
4        2.0                 1                  0  ...       0       0   
...      ...               ...                ...  ...     ...     ...   
4272     0.0                 1                  0  ...       0       0   
4273   144.0                 1                  0  ...       0       0   
4274     0.0                 0                  0  ...       0       0   
4275   523.0                 0                  1  ...       0       0   
4276     0.0                 1                  0  ...       0       0   

      Deck_C  Deck_D  Deck_E  Deck_F  Deck_G  Deck_T  side_P  side_S  
0          0       0       0       0       0       0       1       0  
1          0       0       0       1       0       0       0       1  
2          0       0       0       0       0       0       0       1  
3          0       0       0       0       0       0       0       1  
4          0       0       0       1       0       0       0       1  
...      ...     ...     ...     ...     ...     ...     ...     ...  
4272       0       0       0       0       1       0       0       1  
4273       0       0       0       1       0       0       0       1  
4274       0       1       0       0       0       0       1       0  
4275       0       1       0       0       0       0       1       0  
4276       0       0       0       0       1       0       0       1  

[12970 rows x 24 columns]

In [194]:
from sklearn.preprocessing import OneHotEncoder
# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# passing bridge-types-cat column (label encoded values of bridge_types)
enc_df = pd.DataFrame(enc.fit_transform(df_final1[['HomePlanet','Destination']]).toarray())
# merge with main df bridge_df on key values
df_final1 = df_final1.join(enc_df)
df_final1

HomePlanet  CryoSleep    Destination   Age    VIP  RoomService  \
0        Europa      False    TRAPPIST-1e  39.0  False          0.0   
0         Earth       True    TRAPPIST-1e  27.0  False          0.0   
1         Earth      False    TRAPPIST-1e  24.0  False        109.0   
1         Earth      False    TRAPPIST-1e  19.0  False          0.0   
2        Europa      False    TRAPPIST-1e  58.0   True         43.0   
...         ...        ...            ...   ...    ...          ...   
8688     Europa      False    55 Cancri e  41.0   True          0.0   
8689      Earth       True  PSO J318.5-22  18.0  False          0.0   
8690      Earth      False    TRAPPIST-1e  26.0  False          0.0   
8691     Europa      False    55 Cancri e  32.0  False          0.0   
8692     Europa      False    TRAPPIST-1e  44.0  False        126.0   

      FoodCourt  ShoppingMall     Spa  VRDeck Deck side    0    1    2    3  \
0           0.0           0.0     0.0     0.0    B    P  0.0  1.0  0.0  0.0   
0           0.0           0.0     0.0     0.0    G    S  0.0  1.0  0.0  0.0   
1           9.0          25.0   549.0    44.0    F    S  1.0  0.0  0.0  0.0   
1           9.0           0.0  2823.0     0.0    F    S  1.0  0.0  0.0  0.0   
2        3576.0           0.0  6715.0    49.0    A    S  0.0  1.0  0.0  0.0   
...         ...           ...     ...     ...  ...  ...  ...  ...  ...  ...   
8688     6819.0           0.0  1643.0    74.0    A    P  0.0  1.0  0.0  1.0   
8689        0.0           0.0     0.0     0.0    G    S  1.0  0.0  0.0  0.0   
8690        0.0        1872.0     1.0     0.0    G    S  1.0  0.0  0.0  0.0   
8691     1049.0           0.0   353.0  3235.0    E    S  0.0  1.0  0.0  1.0   
8692     4688.0           0.0     0.0    12.0    E    S  0.0  1.0  0.0  0.0   

        4    5  
0     0.0  1.0  
0     0.0  1.0  
1     0.0  1.0  
1     0.0  1.0  
2     0.0  1.0  
...   ...  ...  
8688  0.0  0.0  
8689  1.0  0.0  
8690  0.0  1.0  
8691  0.0  0.0  
8692  0.0  1.0  

[12970 rows x 18 columns]

In [391]:
df_train =df_final2[:8693]
df_test = df_final2[8693 :]

In [392]:
df_train.shape

(8693, 24)

In [393]:
Y.shape

(8693,)

In [394]:
df_train.columns

Index(['CryoSleep', 'Age', 'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall',
       'Spa', 'VRDeck', 'HomePlanet_Earth', 'HomePlanet_Europa',
       'HomePlanet_Mars', 'Destination_55 Cancri e',
       'Destination_PSO J318.5-22', 'Destination_TRAPPIST-1e', 'Deck_A',
       'Deck_B', 'Deck_C', 'Deck_D', 'Deck_E', 'Deck_F', 'Deck_G', 'Deck_T',
       'side_P', 'side_S'],
      dtype='object')

In [395]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8693 entries, 0 to 8692
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   CryoSleep                  8693 non-null   bool   
 1   Age                        8693 non-null   float64
 2   VIP                        8693 non-null   bool   
 3   RoomService                8693 non-null   float64
 4   FoodCourt                  8693 non-null   float64
 5   ShoppingMall               8693 non-null   float64
 6   Spa                        8693 non-null   float64
 7   VRDeck                     8693 non-null   float64
 8   HomePlanet_Earth           8693 non-null   uint8  
 9   HomePlanet_Europa          8693 non-null   uint8  
 10  HomePlanet_Mars            8693 non-null   uint8  
 11  Destination_55 Cancri e    8693 non-null   uint8  
 12  Destination_PSO J318.5-22  8693 non-null   uint8  
 13  Destination_TRAPPIST-1e    8693 non-null   uint8

In [396]:
df_test.shape

(4277, 24)

In [397]:
# Create training and testing partitions
X_train, X_test, y_train, y_test = train_test_split(df_train, Y, test_size=0.25)

In [398]:
X_train

CryoSleep   Age    VIP  RoomService  FoodCourt  ShoppingMall    Spa  \
3033      False  43.0  False          0.0       16.0          34.0  753.0   
8268      False  19.0  False          0.0        6.0           0.0    0.0   
5587      False  21.0  False        423.0        0.0         172.0    0.0   
3649       True   9.0  False          0.0        0.0           0.0    0.0   
4667       True   2.0  False          0.0        0.0           0.0    0.0   
...         ...   ...    ...          ...        ...           ...    ...   
5329       True  33.0  False          0.0        0.0           0.0    0.0   
5518      False  32.0  False       4518.0      914.0           0.0   93.0   
1851       True  15.0  False          0.0        0.0           0.0    0.0   
1673      False  30.0  False       1220.0        0.0          49.0   39.0   
737        True  26.0  False          0.0        0.0           0.0    0.0   

      VRDeck  HomePlanet_Earth  HomePlanet_Europa  ...  Deck_A  Deck_B  \
3033     1.0                 1                  0  ...       0       0   
8268  1179.0                 1                  0  ...       0       0   
5587     0.0                 1                  0  ...       0       0   
3649     0.0                 1                  0  ...       0       0   
4667     0.0                 1                  0  ...       0       0   
...      ...               ...                ...  ...     ...     ...   
5329     0.0                 1                  0  ...       0       0   
5518     0.0                 1                  0  ...       0       0   
1851     0.0                 0                  1  ...       0       1   
1673     0.0                 0                  0  ...       0       0   
737      0.0                 1                  0  ...       0       0   

      Deck_C  Deck_D  Deck_E  Deck_F  Deck_G  Deck_T  side_P  side_S  
3033       0       0       0       1       0       0       0       1  
8268       0       0       0       1       0       0       0       1  
5587       0       0       0       1       0       0       0       1  
3649       0       0       0       0       1       0       1       0  
4667       0       0       0       0       1       0       0       1  
...      ...     ...     ...     ...     ...     ...     ...     ...  
5329       0       0       0       0       1       0       1       0  
5518       0       0       0       0       1       0       0       1  
1851       0       0       0       0       0       0       0       1  
1673       0       0       0       1       0       0       1       0  
737        0       0       1       0       0       0       0       1  

[6519 rows x 24 columns]

In [399]:
X_train.shape,X_test.shape

((6519, 24), (2174, 24))

In [400]:
y_train.shape

(6519,)

In [401]:
from sklearn.model_selection import GridSearchCV
import xgboost as xgb

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
pipelines = {
    'rf': make_pipeline(StandardScaler(), RandomForestClassifier(random_state=1234)),
    'gb': make_pipeline(StandardScaler(), GradientBoostingClassifier(random_state=1234)),
   
     }

In [402]:
GradientBoostingClassifier().get_params()

{'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'log_loss',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'random_state': None,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [404]:
grid = {
    'rf': {
        'randomforestclassifier__n_estimators':[100,200,300,400,500]
    },
    'gb':{
        'gradientboostingclassifier__n_estimators':[100,200,300,400,500]
    } 
}

In [405]:
pipelines.items()

dict_items([('rf', Pipeline(steps=[('standardscaler', StandardScaler()),
                ('randomforestclassifier',
                 RandomForestClassifier(random_state=1234))])), ('gb', Pipeline(steps=[('standardscaler', StandardScaler()),
                ('gradientboostingclassifier',
                 GradientBoostingClassifier(random_state=1234))]))])

In [406]:
# Create a blank dictionary to hold the models 
fit_models = {}
# Loop through all the algos 
for algo, pipeline in pipelines.items():
  print(f'Training the {algo} model.')
  # Create new Grid Search CV Cclass 
  model = GridSearchCV(pipeline, grid[algo], n_jobs=-1, cv=10)
  # Train the model 
  model.fit(X_train, y_train)
  # Store results inside of the dictionary
  fit_models[algo] = model

Training the rf model.
Training the gb model.


In [407]:
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve,confusion_matrix,roc_auc_score,accuracy_score

In [408]:
# Evaluate the performance of the model 
for algo, model in fit_models.items(): 
  yhat = model.predict(X_test)
  accuracy = accuracy_score(y_test, yhat)
  precision = precision_score(y_test, yhat)
  recall = recall_score(y_test, yhat)
  print(f'Metrics for {algo}: accuracy- {accuracy}, recall- {recall}, precision- {precision}')

Metrics for rf: accuracy- 0.7897884084636615, recall- 0.7713771377137714, precision- 0.8084905660377358
Metrics for gb: accuracy- 0.7994480220791168, recall- 0.8442844284428442, precision- 0.7810158201498751


In [425]:
xgb_model = XGBClassifier(n_estimators= 637,learning_rate=0.01,subsample= 0.6, min_child_weight=1, max_depth=5,objective='binary:logistic')
mod = xgb_model.fit(X_train, y_train,eval_metric='logloss')

print("Performance on train data:", mod.score(X_train, y_train))

y_pred_v2 = xgb_model.predict(X_test)

cm = confusion_matrix(y_test, y_pred_v2) 
print ("Confusion Matrix : \n", cm)

F:\Tensorflowobjectdetection\TFODCourse-main\OBD\lib\site-packages\xgboost\sklearn.py:793: UserWarning: `eval_metric` in `fit` method is deprecated for better compatibility with scikit-learn, use `eval_metric` in constructor or`set_params` instead.
  warnings.warn(


Performance on train data: 0.8315692590888173
Confusion Matrix : 
 [[823 240]
 [187 924]]


In [416]:
rfc_single = RandomForestClassifier(bootstrap= False, n_estimators=529, max_depth=15, min_samples_split=5,min_samples_leaf=4,max_features='auto',verbose=0)
rfc_single.fit(X_train, y_train)

print("Performance on train data:", rfc_single.score(X_train, y_train))

y_pred_v1 = rfc_single.predict(X_test)

cm = confusion_matrix(y_test, y_pred_v1)
 
print ("Confusion Matrix : \n", cm)

F:\Tensorflowobjectdetection\TFODCourse-main\OBD\lib\site-packages\sklearn\ensemble\_forest.py:427: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


Performance on train data: 0.8843380886639055
Confusion Matrix : 
 [[850 213]
 [207 904]]


In [423]:
model = LGBMClassifier(n_estimators=975, min_child_samples=5, max_depth=8, learning_rate=0.01,feature_fraction=0.6, 
                       bagging_freq=5, bagging_fraction= 0.9,objective ='binary')
model.fit(X_train, y_train)

print("Performance on train data:", model.score(X_train, y_train))

y_pred_v = model.predict(X_test)

cm = confusion_matrix(y_test, y_pred_v) 
print ("Confusion Matrix : \n", cm)

[LightGBM] [Warning] feature_fraction is set=0.6, colsample_bytree=1.0 will be ignored. Current value: feature_fraction=0.6
[LightGBM] [Warning] bagging_fraction is set=0.9, subsample=1.0 will be ignored. Current value: bagging_fraction=0.9
[LightGBM] [Warning] bagging_freq is set=5, subsample_freq=0 will be ignored. Current value: bagging_freq=5
Performance on train data: 0.8665439484583525
Confusion Matrix : 
 [[826 237]
 [183 928]]


In [354]:
import pickle


In [414]:
with open('rfx.pkl', 'wb') as f: 
  pickle.dump(rfc_single, f)

In [415]:
with open('rfx.pkl', 'rb') as f: 
  reloaded_model = pickle.load(f)

In [426]:
accuracy = accuracy_score(y_test, y_pred_v2)
precision = precision_score(y_test, y_pred_v2)
recall = recall_score(y_test, y_pred_v2)
print(f'Metrics for {algo}: accuracy- {accuracy}, recall- {recall}, precision- {precision}')

Metrics for gb: accuracy- 0.8035878564857406, recall- 0.8316831683168316, precision- 0.7938144329896907


In [418]:
df_test

CryoSleep   Age    VIP  RoomService  FoodCourt  ShoppingMall     Spa  \
0          True  27.0  False          0.0        0.0           0.0     0.0   
1         False  19.0  False          0.0        9.0           0.0  2823.0   
2          True  31.0  False          0.0        0.0           0.0     0.0   
3         False  38.0  False          0.0     6652.0           0.0   181.0   
4         False  20.0  False         10.0        0.0         635.0     0.0   
...         ...   ...    ...          ...        ...           ...     ...   
4272       True  34.0  False          0.0        0.0           0.0     0.0   
4273      False  42.0  False          0.0      847.0          17.0    10.0   
4274       True  27.0  False          0.0        0.0           0.0     0.0   
4275      False  27.0  False          0.0     2680.0           0.0     0.0   
4276       True  43.0  False          0.0        0.0           0.0     0.0   

      VRDeck  HomePlanet_Earth  HomePlanet_Europa  ...  Deck_A  Deck_B  \
0        0.0                 1                  0  ...       0       0   
1        0.0                 1                  0  ...       0       0   
2        0.0                 0                  1  ...       0       0   
3      585.0                 0                  1  ...       0       0   
4        0.0                 1                  0  ...       0       0   
...      ...               ...                ...  ...     ...     ...   
4272     0.0                 1                  0  ...       0       0   
4273   144.0                 1                  0  ...       0       0   
4274     0.0                 0                  0  ...       0       0   
4275   523.0                 0                  1  ...       0       0   
4276     0.0                 1                  0  ...       0       0   

      Deck_C  Deck_D  Deck_E  Deck_F  Deck_G  Deck_T  side_P  side_S  
0          0       0       0       0       1       0       0       1  
1          0       0       0       1       0       0       0       1  
2          1       0       0       0       0       0       0       1  
3          1       0       0       0       0       0       0       1  
4          0       0       0       1       0       0       0       1  
...      ...     ...     ...     ...     ...     ...     ...     ...  
4272       0       0       0       0       1       0       0       1  
4273       0       0       0       1       0       0       0       1  
4274       0       1       0       0       0       0       1       0  
4275       0       1       0       0       0       0       1       0  
4276       0       0       0       0       1       0       0       1  

[4277 rows x 24 columns]

In [419]:
yhat_test = rfc_single.predict(df_test)

In [420]:
submission = pd.DataFrame([df1['PassengerId'],yhat_test]).T
submission.columns = ['PassengerID', 'Transported']

In [421]:
submission.head()

PassengerID Transported
0     0013_01        True
1     0018_01       False
2     0019_01        True
3     0021_01        True
4     0023_01        True

In [422]:
submission.to_csv('kaggle_submissionmmnb.csv', index=False)
